### ISSUE TITLE
App is Crashing in Android 11 and Above

### ISSUE THREAD

**Issue by ambumpai** [sivakumarswaminthan/ARNavigation#1]
we have tried to execute this code in our android 11 phone, unfortunately app is getting crashed when app launches, for your reference I'm sharing the log

**tested device : Redmi Note 8
version : Android 11**
                       
**Logs**

2023-04-12 12:14:37.521 4704-4704/com.example.ar_map_new E/Mbgl-Mapbox: Error occurred while initializing telemetry
    java.lang.IllegalArgumentException: com.example.ar_map_new: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:402)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:672)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:659)
        at com.mapbox.android.telemetry.AlarmSchedulerFlusher.register(AlarmSchedulerFlusher.java:31)
        at com.mapbox.android.telemetry.MapboxTelemetry.startAlarm(MapboxTelemetry.java:394)
        at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:388)
        at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:132)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:33)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:167)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:64)
        **at com.example.ar_map_new.MyApplication.onCreate(MyApplication.java:14)**
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7231)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8381)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by Alby0n** [comment]
how were you able to build this project ?

**Comment by akashvarde98** [comment]
Able to build the project??
